slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: localization

    # Duong dan map trong install
    map_file_name: /home/hiep0247/hiep_ros2/install/mec_mobile_navigation/share/mec_mobile_navigation/maps/my_map

    map_start_at_dock: true
    scan_topic: /scan
    map_topic: /map
    odom_topic: /odom
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint

    # Giu nguyen cac params tu mapping
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    minimum_time_interval: 0.1
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.45
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: false      # tat loop closing khi localization
    correlation_search_space_dimension: 1.0
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    distance_variance_penalty: 0.5
    angle_variance_penalty: 0.5
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true